import { ChildTags, TagCreatorFunction } from "./ai-ui.js";
type AIUIJSXTag = (keyof HTMLElementTagNameMap | TagCreatorFunction<Element> | AIUIJSX);
type AIUIJSXElement<N extends AIUIJSXTag, C extends ChildTags[]> = N extends TagCreatorFunction<Element> ? ReturnType<TagCreatorFunction<Element>> : N extends string ? ReturnType<TagCreatorFunction<Element>> : N extends AIUIJSX ? C : never;
type AIUIJSX = <T extends {}, N extends AIUIJSXTag, C extends ChildTags[]>(tagName: N, attrs: T | null, ...children: C) => AIUIJSXElement<N, C>;
declare const AIUIJSX: AIUIJSX;
export declare const jsx: <T extends {
    children?: ChildTags[] | undefined;
}>(tagName: AIUIJSXTag, attrs: T) => {
    readonly attributes: NamedNodeMap;
    readonly classList: DOMTokenList;
    className: string;
    readonly clientHeight: number;
    readonly clientLeft: number;
    readonly clientTop: number;
    readonly clientWidth: number;
    id: string;
    readonly localName: string;
    readonly namespaceURI: string | null;
    onfullscreenchange: ((this: Element, ev: Event) => any) | null;
    onfullscreenerror: ((this: Element, ev: Event) => any) | null;
    outerHTML: string;
    readonly ownerDocument: Document;
    readonly part: DOMTokenList;
    readonly prefix: string | null;
    readonly scrollHeight: number;
    scrollLeft: number;
    scrollTop: number;
    readonly scrollWidth: number;
    readonly shadowRoot: ShadowRoot | null;
    slot: string;
    readonly tagName: string;
    attachShadow: (init: ShadowRootInit) => ShadowRoot;
    checkVisibility: (options?: CheckVisibilityOptions | undefined) => boolean;
    closest: {
        <K extends keyof HTMLElementTagNameMap>(selector: K): HTMLElementTagNameMap[K] | null;
        <K_1 extends keyof SVGElementTagNameMap>(selector: K_1): SVGElementTagNameMap[K_1] | null;
        <K_2 extends keyof MathMLElementTagNameMap>(selector: K_2): MathMLElementTagNameMap[K_2] | null;
        <E extends Element = Element>(selectors: string): E | null;
    };
    computedStyleMap: () => StylePropertyMapReadOnly;
    getAttribute: (qualifiedName: string) => string | null;
    getAttributeNS: (namespace: string | null, localName: string) => string | null;
    getAttributeNames: () => string[];
    getAttributeNode: (qualifiedName: string) => Attr | null;
    getAttributeNodeNS: (namespace: string | null, localName: string) => Attr | null;
    getBoundingClientRect: () => DOMRect;
    getClientRects: () => DOMRectList;
    getElementsByClassName: (classNames: string) => HTMLCollectionOf<Element>;
    getElementsByTagName: {
        <K_3 extends keyof HTMLElementTagNameMap>(qualifiedName: K_3): HTMLCollectionOf<HTMLElementTagNameMap[K_3]>;
        <K_4 extends keyof SVGElementTagNameMap>(qualifiedName: K_4): HTMLCollectionOf<SVGElementTagNameMap[K_4]>;
        <K_5 extends keyof MathMLElementTagNameMap>(qualifiedName: K_5): HTMLCollectionOf<MathMLElementTagNameMap[K_5]>;
        <K_6 extends keyof HTMLElementDeprecatedTagNameMap>(qualifiedName: K_6): HTMLCollectionOf<HTMLElementDeprecatedTagNameMap[K_6]>;
        (qualifiedName: string): HTMLCollectionOf<Element>;
    };
    getElementsByTagNameNS: {
        (namespaceURI: "http://www.w3.org/1999/xhtml", localName: string): HTMLCollectionOf<HTMLElement>;
        (namespaceURI: "http://www.w3.org/2000/svg", localName: string): HTMLCollectionOf<SVGElement>;
        (namespaceURI: "http://www.w3.org/1998/Math/MathML", localName: string): HTMLCollectionOf<MathMLElement>;
        (namespace: string | null, localName: string): HTMLCollectionOf<Element>;
    };
    hasAttribute: (qualifiedName: string) => boolean;
    hasAttributeNS: (namespace: string | null, localName: string) => boolean;
    hasAttributes: () => boolean;
    hasPointerCapture: (pointerId: number) => boolean;
    insertAdjacentElement: (where: InsertPosition, element: Element) => Element | null;
    insertAdjacentHTML: (position: InsertPosition, text: string) => void;
    insertAdjacentText: (where: InsertPosition, data: string) => void;
    matches: (selectors: string) => boolean;
    releasePointerCapture: (pointerId: number) => void;
    removeAttribute: (qualifiedName: string) => void;
    removeAttributeNS: (namespace: string | null, localName: string) => void;
    removeAttributeNode: (attr: Attr) => Attr;
    requestFullscreen: (options?: FullscreenOptions | undefined) => Promise<void>;
    requestPointerLock: () => void;
    scroll: {
        (options?: ScrollToOptions | undefined): void;
        (x: number, y: number): void;
    };
    scrollBy: {
        (options?: ScrollToOptions | undefined): void;
        (x: number, y: number): void;
    };
    scrollIntoView: (arg?: boolean | ScrollIntoViewOptions | undefined) => void;
    scrollTo: {
        (options?: ScrollToOptions | undefined): void;
        (x: number, y: number): void;
    };
    setAttribute: (qualifiedName: string, value: string) => void;
    setAttributeNS: (namespace: string | null, qualifiedName: string, value: string) => void;
    setAttributeNode: (attr: Attr) => Attr | null;
    setAttributeNodeNS: (attr: Attr) => Attr | null;
    setPointerCapture: (pointerId: number) => void;
    toggleAttribute: (qualifiedName: string, force?: boolean | undefined) => boolean;
    webkitMatchesSelector: (selectors: string) => boolean;
    addEventListener: {
        <K_7 extends keyof ElementEventMap>(type: K_7, listener: (this: Element, ev: ElementEventMap[K_7]) => any, options?: boolean | AddEventListenerOptions | undefined): void;
        (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions | undefined): void;
    };
    removeEventListener: {
        <K_8 extends keyof ElementEventMap>(type: K_8, listener: (this: Element, ev: ElementEventMap[K_8]) => any, options?: boolean | EventListenerOptions | undefined): void;
        (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions | undefined): void;
    };
    readonly baseURI: string;
    readonly childNodes: NodeListOf<ChildNode>;
    readonly firstChild: ChildNode | null;
    readonly isConnected: boolean;
    readonly lastChild: ChildNode | null;
    readonly nextSibling: ChildNode | null;
    readonly nodeName: string;
    readonly nodeType: number;
    nodeValue: string | null;
    readonly parentElement: HTMLElement | null;
    readonly parentNode: ParentNode | null;
    readonly previousSibling: ChildNode | null;
    textContent: string | null;
    appendChild: <T_1 extends Node>(node: T_1) => T_1;
    cloneNode: (deep?: boolean | undefined) => Node;
    compareDocumentPosition: (other: Node) => number;
    contains: (other: Node | null) => boolean;
    getRootNode: (options?: GetRootNodeOptions | undefined) => Node;
    hasChildNodes: () => boolean;
    insertBefore: <T_2 extends Node>(node: T_2, child: Node | null) => T_2;
    isDefaultNamespace: (namespace: string | null) => boolean;
    isEqualNode: (otherNode: Node | null) => boolean;
    isSameNode: (otherNode: Node | null) => boolean;
    lookupNamespaceURI: (prefix: string | null) => string | null;
    lookupPrefix: (namespace: string | null) => string | null;
    normalize: () => void;
    removeChild: <T_3 extends Node>(child: T_3) => T_3;
    replaceChild: <T_4 extends Node>(node: Node, child: T_4) => T_4;
    readonly ELEMENT_NODE: 1;
    readonly ATTRIBUTE_NODE: 2;
    readonly TEXT_NODE: 3;
    readonly CDATA_SECTION_NODE: 4;
    readonly ENTITY_REFERENCE_NODE: 5;
    readonly ENTITY_NODE: 6;
    readonly PROCESSING_INSTRUCTION_NODE: 7;
    readonly COMMENT_NODE: 8;
    readonly DOCUMENT_NODE: 9;
    readonly DOCUMENT_TYPE_NODE: 10;
    readonly DOCUMENT_FRAGMENT_NODE: 11;
    readonly NOTATION_NODE: 12;
    readonly DOCUMENT_POSITION_DISCONNECTED: 1;
    readonly DOCUMENT_POSITION_PRECEDING: 2;
    readonly DOCUMENT_POSITION_FOLLOWING: 4;
    readonly DOCUMENT_POSITION_CONTAINS: 8;
    readonly DOCUMENT_POSITION_CONTAINED_BY: 16;
    readonly DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: 32;
    dispatchEvent: (event: Event) => boolean;
    ariaAtomic: string | null;
    ariaAutoComplete: string | null;
    ariaBusy: string | null;
    ariaChecked: string | null;
    ariaColCount: string | null;
    ariaColIndex: string | null;
    ariaColSpan: string | null;
    ariaCurrent: string | null;
    ariaDescription: string | null;
    ariaDisabled: string | null;
    ariaExpanded: string | null;
    ariaHasPopup: string | null;
    ariaHidden: string | null;
    ariaInvalid: string | null;
    ariaKeyShortcuts: string | null;
    ariaLabel: string | null;
    ariaLevel: string | null;
    ariaLive: string | null;
    ariaModal: string | null;
    ariaMultiLine: string | null;
    ariaMultiSelectable: string | null;
    ariaOrientation: string | null;
    ariaPlaceholder: string | null;
    ariaPosInSet: string | null;
    ariaPressed: string | null;
    ariaReadOnly: string | null;
    ariaRequired: string | null;
    ariaRoleDescription: string | null;
    ariaRowCount: string | null;
    ariaRowIndex: string | null;
    ariaRowSpan: string | null;
    ariaSelected: string | null;
    ariaSetSize: string | null;
    ariaSort: string | null;
    ariaValueMax: string | null;
    ariaValueMin: string | null;
    ariaValueNow: string | null;
    ariaValueText: string | null;
    role: string | null;
    animate: (keyframes: Keyframe[] | PropertyIndexedKeyframes | null, options?: number | KeyframeAnimationOptions | undefined) => Animation;
    getAnimations: (options?: GetAnimationsOptions | undefined) => Animation[];
    after: (...nodes: (string | Node)[]) => void;
    before: (...nodes: (string | Node)[]) => void;
    remove: () => void;
    replaceWith: (...nodes: (string | Node)[]) => void;
    innerHTML: string;
    readonly nextElementSibling: Element | null;
    readonly previousElementSibling: Element | null;
    readonly childElementCount: number;
    readonly children: HTMLCollection;
    readonly firstElementChild: Element | null;
    readonly lastElementChild: Element | null;
    append: (...nodes: (string | Node)[]) => void;
    prepend: (...nodes: (string | Node)[]) => void;
    querySelector: {
        <K_9 extends keyof HTMLElementTagNameMap>(selectors: K_9): HTMLElementTagNameMap[K_9] | null;
        <K_10 extends keyof SVGElementTagNameMap>(selectors: K_10): SVGElementTagNameMap[K_10] | null;
        <K_11 extends keyof MathMLElementTagNameMap>(selectors: K_11): MathMLElementTagNameMap[K_11] | null;
        <K_12 extends keyof HTMLElementDeprecatedTagNameMap>(selectors: K_12): HTMLElementDeprecatedTagNameMap[K_12] | null;
        <E_1 extends Element = Element>(selectors: string): E_1 | null;
    };
    querySelectorAll: {
        <K_13 extends keyof HTMLElementTagNameMap>(selectors: K_13): NodeListOf<HTMLElementTagNameMap[K_13]>;
        <K_14 extends keyof SVGElementTagNameMap>(selectors: K_14): NodeListOf<SVGElementTagNameMap[K_14]>;
        <K_15 extends keyof MathMLElementTagNameMap>(selectors: K_15): NodeListOf<MathMLElementTagNameMap[K_15]>;
        <K_16 extends keyof HTMLElementDeprecatedTagNameMap>(selectors: K_16): NodeListOf<HTMLElementDeprecatedTagNameMap[K_16]>;
        <E_2 extends Element = Element>(selectors: string): NodeListOf<E_2>;
    };
    replaceChildren: (...nodes: (string | Node)[]) => void;
    readonly assignedSlot: HTMLSlotElement | null;
} | [ChildTags[] | undefined];
export declare const jsxs: <T extends {
    children?: ChildTags[] | undefined;
}>(tagName: AIUIJSXTag, attrs: T) => {
    readonly attributes: NamedNodeMap;
    readonly classList: DOMTokenList;
    className: string;
    readonly clientHeight: number;
    readonly clientLeft: number;
    readonly clientTop: number;
    readonly clientWidth: number;
    id: string;
    readonly localName: string;
    readonly namespaceURI: string | null;
    onfullscreenchange: ((this: Element, ev: Event) => any) | null;
    onfullscreenerror: ((this: Element, ev: Event) => any) | null;
    outerHTML: string;
    readonly ownerDocument: Document;
    readonly part: DOMTokenList;
    readonly prefix: string | null;
    readonly scrollHeight: number;
    scrollLeft: number;
    scrollTop: number;
    readonly scrollWidth: number;
    readonly shadowRoot: ShadowRoot | null;
    slot: string;
    readonly tagName: string;
    attachShadow: (init: ShadowRootInit) => ShadowRoot;
    checkVisibility: (options?: CheckVisibilityOptions | undefined) => boolean;
    closest: {
        <K extends keyof HTMLElementTagNameMap>(selector: K): HTMLElementTagNameMap[K] | null;
        <K_1 extends keyof SVGElementTagNameMap>(selector: K_1): SVGElementTagNameMap[K_1] | null;
        <K_2 extends keyof MathMLElementTagNameMap>(selector: K_2): MathMLElementTagNameMap[K_2] | null;
        <E extends Element = Element>(selectors: string): E | null;
    };
    computedStyleMap: () => StylePropertyMapReadOnly;
    getAttribute: (qualifiedName: string) => string | null;
    getAttributeNS: (namespace: string | null, localName: string) => string | null;
    getAttributeNames: () => string[];
    getAttributeNode: (qualifiedName: string) => Attr | null;
    getAttributeNodeNS: (namespace: string | null, localName: string) => Attr | null;
    getBoundingClientRect: () => DOMRect;
    getClientRects: () => DOMRectList;
    getElementsByClassName: (classNames: string) => HTMLCollectionOf<Element>;
    getElementsByTagName: {
        <K_3 extends keyof HTMLElementTagNameMap>(qualifiedName: K_3): HTMLCollectionOf<HTMLElementTagNameMap[K_3]>;
        <K_4 extends keyof SVGElementTagNameMap>(qualifiedName: K_4): HTMLCollectionOf<SVGElementTagNameMap[K_4]>;
        <K_5 extends keyof MathMLElementTagNameMap>(qualifiedName: K_5): HTMLCollectionOf<MathMLElementTagNameMap[K_5]>;
        <K_6 extends keyof HTMLElementDeprecatedTagNameMap>(qualifiedName: K_6): HTMLCollectionOf<HTMLElementDeprecatedTagNameMap[K_6]>;
        (qualifiedName: string): HTMLCollectionOf<Element>;
    };
    getElementsByTagNameNS: {
        (namespaceURI: "http://www.w3.org/1999/xhtml", localName: string): HTMLCollectionOf<HTMLElement>;
        (namespaceURI: "http://www.w3.org/2000/svg", localName: string): HTMLCollectionOf<SVGElement>;
        (namespaceURI: "http://www.w3.org/1998/Math/MathML", localName: string): HTMLCollectionOf<MathMLElement>;
        (namespace: string | null, localName: string): HTMLCollectionOf<Element>;
    };
    hasAttribute: (qualifiedName: string) => boolean;
    hasAttributeNS: (namespace: string | null, localName: string) => boolean;
    hasAttributes: () => boolean;
    hasPointerCapture: (pointerId: number) => boolean;
    insertAdjacentElement: (where: InsertPosition, element: Element) => Element | null;
    insertAdjacentHTML: (position: InsertPosition, text: string) => void;
    insertAdjacentText: (where: InsertPosition, data: string) => void;
    matches: (selectors: string) => boolean;
    releasePointerCapture: (pointerId: number) => void;
    removeAttribute: (qualifiedName: string) => void;
    removeAttributeNS: (namespace: string | null, localName: string) => void;
    removeAttributeNode: (attr: Attr) => Attr;
    requestFullscreen: (options?: FullscreenOptions | undefined) => Promise<void>;
    requestPointerLock: () => void;
    scroll: {
        (options?: ScrollToOptions | undefined): void;
        (x: number, y: number): void;
    };
    scrollBy: {
        (options?: ScrollToOptions | undefined): void;
        (x: number, y: number): void;
    };
    scrollIntoView: (arg?: boolean | ScrollIntoViewOptions | undefined) => void;
    scrollTo: {
        (options?: ScrollToOptions | undefined): void;
        (x: number, y: number): void;
    };
    setAttribute: (qualifiedName: string, value: string) => void;
    setAttributeNS: (namespace: string | null, qualifiedName: string, value: string) => void;
    setAttributeNode: (attr: Attr) => Attr | null;
    setAttributeNodeNS: (attr: Attr) => Attr | null;
    setPointerCapture: (pointerId: number) => void;
    toggleAttribute: (qualifiedName: string, force?: boolean | undefined) => boolean;
    webkitMatchesSelector: (selectors: string) => boolean;
    addEventListener: {
        <K_7 extends keyof ElementEventMap>(type: K_7, listener: (this: Element, ev: ElementEventMap[K_7]) => any, options?: boolean | AddEventListenerOptions | undefined): void;
        (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions | undefined): void;
    };
    removeEventListener: {
        <K_8 extends keyof ElementEventMap>(type: K_8, listener: (this: Element, ev: ElementEventMap[K_8]) => any, options?: boolean | EventListenerOptions | undefined): void;
        (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions | undefined): void;
    };
    readonly baseURI: string;
    readonly childNodes: NodeListOf<ChildNode>;
    readonly firstChild: ChildNode | null;
    readonly isConnected: boolean;
    readonly lastChild: ChildNode | null;
    readonly nextSibling: ChildNode | null;
    readonly nodeName: string;
    readonly nodeType: number;
    nodeValue: string | null;
    readonly parentElement: HTMLElement | null;
    readonly parentNode: ParentNode | null;
    readonly previousSibling: ChildNode | null;
    textContent: string | null;
    appendChild: <T_1 extends Node>(node: T_1) => T_1;
    cloneNode: (deep?: boolean | undefined) => Node;
    compareDocumentPosition: (other: Node) => number;
    contains: (other: Node | null) => boolean;
    getRootNode: (options?: GetRootNodeOptions | undefined) => Node;
    hasChildNodes: () => boolean;
    insertBefore: <T_2 extends Node>(node: T_2, child: Node | null) => T_2;
    isDefaultNamespace: (namespace: string | null) => boolean;
    isEqualNode: (otherNode: Node | null) => boolean;
    isSameNode: (otherNode: Node | null) => boolean;
    lookupNamespaceURI: (prefix: string | null) => string | null;
    lookupPrefix: (namespace: string | null) => string | null;
    normalize: () => void;
    removeChild: <T_3 extends Node>(child: T_3) => T_3;
    replaceChild: <T_4 extends Node>(node: Node, child: T_4) => T_4;
    readonly ELEMENT_NODE: 1;
    readonly ATTRIBUTE_NODE: 2;
    readonly TEXT_NODE: 3;
    readonly CDATA_SECTION_NODE: 4;
    readonly ENTITY_REFERENCE_NODE: 5;
    readonly ENTITY_NODE: 6;
    readonly PROCESSING_INSTRUCTION_NODE: 7;
    readonly COMMENT_NODE: 8;
    readonly DOCUMENT_NODE: 9;
    readonly DOCUMENT_TYPE_NODE: 10;
    readonly DOCUMENT_FRAGMENT_NODE: 11;
    readonly NOTATION_NODE: 12;
    readonly DOCUMENT_POSITION_DISCONNECTED: 1;
    readonly DOCUMENT_POSITION_PRECEDING: 2;
    readonly DOCUMENT_POSITION_FOLLOWING: 4;
    readonly DOCUMENT_POSITION_CONTAINS: 8;
    readonly DOCUMENT_POSITION_CONTAINED_BY: 16;
    readonly DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: 32;
    dispatchEvent: (event: Event) => boolean;
    ariaAtomic: string | null;
    ariaAutoComplete: string | null;
    ariaBusy: string | null;
    ariaChecked: string | null;
    ariaColCount: string | null;
    ariaColIndex: string | null;
    ariaColSpan: string | null;
    ariaCurrent: string | null;
    ariaDescription: string | null;
    ariaDisabled: string | null;
    ariaExpanded: string | null;
    ariaHasPopup: string | null;
    ariaHidden: string | null;
    ariaInvalid: string | null;
    ariaKeyShortcuts: string | null;
    ariaLabel: string | null;
    ariaLevel: string | null;
    ariaLive: string | null;
    ariaModal: string | null;
    ariaMultiLine: string | null;
    ariaMultiSelectable: string | null;
    ariaOrientation: string | null;
    ariaPlaceholder: string | null;
    ariaPosInSet: string | null;
    ariaPressed: string | null;
    ariaReadOnly: string | null;
    ariaRequired: string | null;
    ariaRoleDescription: string | null;
    ariaRowCount: string | null;
    ariaRowIndex: string | null;
    ariaRowSpan: string | null;
    ariaSelected: string | null;
    ariaSetSize: string | null;
    ariaSort: string | null;
    ariaValueMax: string | null;
    ariaValueMin: string | null;
    ariaValueNow: string | null;
    ariaValueText: string | null;
    role: string | null;
    animate: (keyframes: Keyframe[] | PropertyIndexedKeyframes | null, options?: number | KeyframeAnimationOptions | undefined) => Animation;
    getAnimations: (options?: GetAnimationsOptions | undefined) => Animation[];
    after: (...nodes: (string | Node)[]) => void;
    before: (...nodes: (string | Node)[]) => void;
    remove: () => void;
    replaceWith: (...nodes: (string | Node)[]) => void;
    innerHTML: string;
    readonly nextElementSibling: Element | null;
    readonly previousElementSibling: Element | null;
    readonly childElementCount: number;
    readonly children: HTMLCollection;
    readonly firstElementChild: Element | null;
    readonly lastElementChild: Element | null;
    append: (...nodes: (string | Node)[]) => void;
    prepend: (...nodes: (string | Node)[]) => void;
    querySelector: {
        <K_9 extends keyof HTMLElementTagNameMap>(selectors: K_9): HTMLElementTagNameMap[K_9] | null;
        <K_10 extends keyof SVGElementTagNameMap>(selectors: K_10): SVGElementTagNameMap[K_10] | null;
        <K_11 extends keyof MathMLElementTagNameMap>(selectors: K_11): MathMLElementTagNameMap[K_11] | null;
        <K_12 extends keyof HTMLElementDeprecatedTagNameMap>(selectors: K_12): HTMLElementDeprecatedTagNameMap[K_12] | null;
        <E_1 extends Element = Element>(selectors: string): E_1 | null;
    };
    querySelectorAll: {
        <K_13 extends keyof HTMLElementTagNameMap>(selectors: K_13): NodeListOf<HTMLElementTagNameMap[K_13]>;
        <K_14 extends keyof SVGElementTagNameMap>(selectors: K_14): NodeListOf<SVGElementTagNameMap[K_14]>;
        <K_15 extends keyof MathMLElementTagNameMap>(selectors: K_15): NodeListOf<MathMLElementTagNameMap[K_15]>;
        <K_16 extends keyof HTMLElementDeprecatedTagNameMap>(selectors: K_16): NodeListOf<HTMLElementDeprecatedTagNameMap[K_16]>;
        <E_2 extends Element = Element>(selectors: string): NodeListOf<E_2>;
    };
    replaceChildren: (...nodes: (string | Node)[]) => void;
    readonly assignedSlot: HTMLSlotElement | null;
} | [ChildTags[] | undefined];
export declare const Fragment: AIUIJSX;
declare global {
    var React: unknown;
    namespace JSX {
        type Element = AIUIJSXElement<keyof HTMLElementTagNameMap | TagCreatorFunction<any>, ChildTags[]>;
        type IntrinsicElements = {
            [K in keyof HTMLElementTagNameMap]: Partial<HTMLElementTagNameMap[K]>;
        };
    }
}
declare const _default: {
    AIUIJSX: AIUIJSX;
};
export default _default;
